### ISSUE TITLE
Relacionar PurchaseOrder y Cart

### ISSUE THREAD

**Issue by ahumadamob** [ahumadamob/2024_gc_p3_g1_sf#21]
**Relación entre `purchaseorder` y `cart`**:

* Una orden de compra puede estar asociada con uno o varios carritos.
* Un carrito puede estar asociado con solo una orden de compra (suponiendo que una vez que se realice la compra, el carrito se vacía).
* Esto sugiere una relación de uno a muchos, donde la clave primaria de la tabla `purchaseorder` se relaciona con una clave foránea en la tabla `cart`.

Por favor, proporciona una captura de pantalla del diagrama de tablas generado al iniciar la aplicación, mostrando la estructura de las tablas que se han creado.

Renombra el atributo `id_order` por `id` en la entidad `PurchaseOrder`

**Comment by ahumadamob** [comment]
Continúa con comentarios! Por favor, revisar periodicamente

**Comment by edumanucha** [comment]
![image](https://github.com/ahumadamob/2024_gc_p3_g1_sf/assets/92409155/5a27a203-d69c-4012-a9c0-8be264cec009)
