### ISSUE TITLE
Recuperatorio Eduardo Manucha

### ISSUE THREAD

**Issue by ahumadamob** [ahumadamob/2024_gc_p3_g1_sf#44]
Reparar todos los errores y warnings de la rama actual

**Comment by edumanucha** [comment]
Buena noche profesor , el único warning que me aparece en el spring tool está en el RatingRepository.java

![Captura del warnig para mostrar en git](https://github.com/ahumadamob/2024_gc_p3_g1_sf/assets/92409155/0000d7ae-569f-431b-a102-116c8d029a6b)

¿Me puede indicar si a usted en su ide, le aparece warning o error?

**Comment by edumanucha** [comment]
Agrego otro warning 
me aparecía uno por la versión de spring
captura con el warning

![pom xml con warning](https://github.com/ahumadamob/2024_gc_p3_g1_sf/assets/92409155/42912903-d1d1-4acb-a907-dcf3e57b515e)


luego de modificar la versión , se eliminó el warning

![pom xml sin warning](https://github.com/ahumadamob/2024_gc_p3_g1_sf/assets/92409155/8a844b77-54ba-4090-9f6a-a5b7cb6441bf)
